### PR TITLE
feat: read alterId from config and support multiple clients in `clients.py`

### PR DESCRIPTION
**Pull request by mjafari98**
- Print all vmess client links
- Add all vmess client links in web/html
- Read alterId from `config.json` (instead of hardcoded `"0"`)

### CODE REVIEW

**Comment by miladrahimi** [comment]
The default config does not support multiple vmess/ss servers so this python script doesn't need to support such feature

**Comment by mjafari98** [comment]
As you can see in `clients` section, v2ray config supports multiple vmess clients. This PR includes them all; and also is compatible with the single client mode. Another bug which is fixed, is the `alterId` which is hardcoded as `"0"` in this script which obviously can cause problems.

**Comment by MJamshidnejad** [comment]
> * Print all vmess client links
> * Add all vmess client links in web/html
> * Read alterId from `config.json` (instead of hardcoded `"0"`)

I have to mention non-zero `alterid` is not supported by newer version.

**Comment by miladrahimi** [comment]
It's deprecated so you shoudn't use it.

**Pull request closed without merging**
